Safari.Web/Pages/Details.cshtml.cs
//File: Details.cshtml.cs
//Class: DetailsPageModel
//Description: This class is the code behind for the Details.cshtml page. It is used to display the details of a selected animal.

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Safari.Data;

namespace Safari.Web.Pages
{
    public class DetailsPageModel : PageModel
    {
        private readonly WildlifeDataContext _context;
                
        public Animal Animal { get; set; } = default!;
        public string AnimalDescription { get; set; } = default!;
        public List<AnimalPic> AnimalPics { get; set; } = default!;
        public List<string> AnimalStates { get; set; } = default!;
        public bool PicExists { get; set; } = default!;

        //Constructor
        public DetailsPageModel(WildlifeDataContext context)
        {
            _context = context;
        }

        //OnGetAsync: On HTTP GET, this method gets the animal details from the database so they can be displayed.
        public async Task<IActionResult> OnGetAsync(int? id)
        {
            //If the id is blank or the animal is not found, return a 404 error.
            if (id == null || _context.Animal == null)
            {
                return NotFound();
            }

            //Locate the animal in the database.
            var animal = await _context.Animal.FirstOrDefaultAsync(m => m.AnimalId == id);

            //If the animal cannot be located in the database, return a 404 error.
            if (animal == null)
            {
                return NotFound();
            }
            else
            {
                Animal = animal;
            }

            //Set the AnimalDescription, AnimalPics, and AnimalStates properties.
            AnimalDescription = _context.AnimalDescription.Where(a => a.AnimalId == id).FirstOrDefault().Description;
            AnimalPics = _context.AnimalPic.Where(a => a.AnimalId == id).ToList();
            AnimalStates = _context.AnimalState.Where(a => a.AnimalId == id).Select(a => a.State.Name).ToList();

            //Set the PicExists property, which keeps track of whether or not the animal has any pictures.
            PicExists = AnimalPics.Count > 0;
            
            return Page();
        }
    }
}

Safari.Web/Pages/Error.cshtml.cs
//File: Error.cshtml.cs
//Class: ErrorModel
//Description: This is the code-behind for the Error page, which is displayed when an error occurs in the application.
//It has not been modified from its original ASP.NET Core scaffolding.

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Safari.Web.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Safari.Web/Pages/Index.cshtml.cs
//File: Index.cshtml.cs
//Class: IndexPageModel
//Description: This is the code-behind class for the Index page. It is used to handle the GET request for the Index page.
//Beyond tracking usage by logging, this class does not do anything else, and may be removed in the future.

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Safari.Web.Pages
{
    public class IndexPageModel : PageModel
    {
        private readonly ILogger<IndexPageModel> _logger;

        public IndexPageModel(ILogger<IndexPageModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Safari.Web/Pages/Map.cshtml.cs
//File: Map.cshtml.cs
//Class: MapPageModel
//Description: This is the code-behind class for the Map page. It generates a list of animals to display.

using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Safari.Data;
using Safari.Web.ViewModels;

namespace Safari.Web.Pages;

public class MapPageModel : PageModel
{
    private readonly WildlifeDataContext _context;
    private readonly IMapper _mapper;

    //Constructor
    public MapPageModel(WildlifeDataContext context, IMapper mapper)
    {
        _context = context;
        _mapper = mapper;
    }

    //This property is a list of AnimalViewModel objects. AnimalViewModel is a view model class that
    //contains data from the Animal model, with some modifications to make it easier to display.
    public IList<AnimalViewModel> Animal { get; set; } = default!;

    public async Task OnGetAsync()
    {
        if (_context.Animal != null)
        {
            // The Interactive Map page model pulls information to AnimalViewModel,
            // just like the View All Animals page. Clicking a state on the map
            // then triggers a DataTables Search to filter the results by state.
            var animals = await _context.Animal
            .Include(a => a.AnimalType)
            .Include(a => a.DietType)
            .Include(a => a.AnimalPic)
            .Include(a => a.AnimalState)
                .ThenInclude(AnimalState => AnimalState.State)
            .ToListAsync();

            // Map Animal to AnimalViewModel (populate data from Animal to AnimalViewModel)
            Animal = _mapper.Map<IList<AnimalViewModel>>(animals);
        }
    }
}

Safari.Web/Pages/References.cshtml.cs
//File: References.cshtml.cs
//Class: ReferencesPageModel
//Description: This is the code-behind class for the References page. The class currently adds no additional code and may be removed in the future.

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Safari.Web.Pages
{
    public class ReferencesPageModel : PageModel
    {        
        
        public void OnGet()
        {
        }
    }
}

Safari.Web/Pages/SubmitAnimal.cshtml.cs
//File: SubmitAnimal.cshtml.cs
//Class: SubmitAnimalPageModel
//Description: This is the code-behind class for the Submit Animal page, which allows users to submit animals to the database.

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Safari.Data;
using System.ComponentModel.DataAnnotations;

namespace Safari.Web.Pages;

public class SubmitAnimalPageModel : PageModel
{
    private readonly WildlifeDataContext _context;
    private readonly IWildlifeRepository _repository;

    //Constructor
    public SubmitAnimalPageModel(WildlifeDataContext context, IWildlifeRepository repository)
    {
        _context = context;
        _repository = repository;
    }

    [BindProperty]
    public Animal Animal { get; set; } = default!;

    [BindProperty]
    [Required(ErrorMessage = "Please select at least one state.")]
    public List<int> SelectedStateIds { get; set; } = default!;

    [BindProperty]
    public AnimalDescription AnimalDescription { get; set; } = default!;

    [BindProperty]
    public AnimalPic AnimalPic { get; set; } = default!;

    //*************
    //Reusable Code
    //*************
    //RepopulateViewData: This method repopulates the ViewData for the page whenever the page is refreshed/loaded.
    //Instead of copying this code into every GET and POST method, it is placed here and called whenever needed,
    //reducing the amount of code needed.
    public void RepopulateViewData()
    {
        ViewData["AnimalTypeId"] = new SelectList(
                           _context.AnimalType, "AnimalTypeId", "Name");
        ViewData["DietTypeId"] = new SelectList(
                           _context.DietType, "DietTypeId", "Name");
        ViewData["StateId"] = new SelectList(
                           _context.State, "StateId", "Name");
    }

    //OnGet: On HTTP GET, populate the view data and return the page
    public IActionResult OnGet()
    {
        RepopulateViewData();
        return Page();
    }

    //OnPostResetForm: On HTTP POST, if the user clicks the "Reset Form" button, reset the form and return the page
    public IActionResult OnPostResetForm()
    {
        // Reset the model properties to their default values
        Animal = new Animal();
        SelectedStateIds = new List<int>();
        AnimalDescription = new AnimalDescription();
        AnimalPic = new AnimalPic();

        // Clear model state errors
        ModelState.Clear();

        // Repopulate the view and return to the page
        RepopulateViewData();
        return Page();
    }

    //OnPostAsync: On HTTP POST, if the user clicks the "Submit" button, try to submit the animal to the database.
    public async Task<IActionResult> OnPostAsync()
    {
        // If the model state is invalid for any other reason, cancel the post
        if (!ModelState.IsValid)
        {
            RepopulateViewData();
            return Page();
        }

        //Create a variable to store the new animal's ID. This ID is set after adding a record to the Animal table,
        //and is used when adding records to the AnimalState, AnimalDescription, and AnimalPic tables.
        int NewAnimalID = 0;

        //Begin transaction
        using var transaction = await _context.Database.BeginTransactionAsync();

        try
        {
            // Execute the insert_animal stored procedure
            NewAnimalID = await _repository.AddAnimalAsync(Animal);

            //Execute the insert_animalstate stored procedure
            foreach (var StateID in SelectedStateIds)
            {
                await _repository.AddAnimalStateAsync(NewAnimalID, StateID);
            }

            // If the description is null, set it to "No description provided."
            if (AnimalDescription.Description == null)
            {
                AnimalDescription.Description = "No description provided.";
            }
            await _repository.AddAnimalDescriptionAsync(NewAnimalID, AnimalDescription);

            if (AnimalPic.File != null)
            {
                // Generate a unique file name for the uploaded image
                // Format is AnimalID + "_" + Name + "_1" + extension,
                // where 1 indicates the number of images. Since this is the first image, the number is 1.
                // This is stored in the database.
                AnimalPic.FileName = $"{NewAnimalID}_{Animal.Name}_1{Path.GetExtension(AnimalPic.File.FileName)}";

                // Set the file path to the "images" folder in the wwwroot directory
                // This is stored in the database.
                AnimalPic.FilePath = Path.Combine("images", AnimalPic.FileName);

                // Save the uploaded file to the images folder.
                var FullPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", AnimalPic.FilePath);
                using (var FileStream = new FileStream(FullPath, FileMode.Create))
                {
                    await AnimalPic.File.CopyToAsync(FileStream);
                }

                // Save the AnimalPic object to the database
                await _repository.AddAnimalPicAsync(NewAnimalID, AnimalPic);
            }

            //Commit the transaction
            await transaction.CommitAsync();
            TempData["SuccessMessage"] = "Animal submitted successfully!";
            //Reset the form after submitting, in case the user wants to submit another animal
            OnPostResetForm();
            return Page();
        }
        //Catch any SQL exceptions: rollback the transaction and display an error message on the Submit page.
        catch (SqlException ex)
        {
            TempData["ErrorMessage"] = ex.Message;
            //Rollback the transaction
            await transaction.RollbackAsync();
            RepopulateViewData();
            return Page();
        }
    }
}

Safari.Web/Pages/SubmitImage.cshtml.cs
//File: SubmitImage.cshtml.cs
//Class: SubmitImagePageModel
//Description: This is the code-behind class for the Submit Image page, which allows users to submit images to the database.

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Safari.Data;

namespace Safari.Web.Pages;

public class SubmitImagePageModel : PageModel
{
    private readonly WildlifeDataContext _context;
    private readonly IWildlifeRepository _repository;

    //Constructor
    public SubmitImagePageModel(WildlifeDataContext context, IWildlifeRepository repository)
    {
        _context = context;
        _repository = repository;
    }

    [BindProperty]
    public AnimalPic AnimalPic { get; set; } = default!;

    //*************
    //Reusable Code
    //*************
    //RepopulateViewData: This method repopulates the ViewData for the page whenever the page is refreshed/loaded.
    //Instead of copying this code into every GET and POST method, it is placed here and called whenever needed,
    //reducing the amount of code needed.
    public void RepopulateViewData()
    {
        ViewData["AnimalId"] = new SelectList(_context.Animal, "AnimalId", "Name");
    }

    //OnGet: On HTTP GET, populate the view data and return the page.
    public IActionResult OnGet()
    {
        RepopulateViewData();
        return Page();
    }

    //OnPostResetForm: On HTTP POST, if the user clicks the "Reset Form" button, reset the form and return the page.
    public IActionResult OnPostResetForm()
    {
        // Reset the model properties to their default values
        AnimalPic = new AnimalPic();

        // Clear model state errors
        ModelState.Clear();

        // Repopulate the view and return to the page
        RepopulateViewData();
        return Page();
    }

    //OnPostAsync: On HTTP POST, if the user clicks the "Submit" button, validate the form and save the data to the database.
    public async Task<IActionResult> OnPostAsync()
    {
        //If the submitted information is invalid for any reason, return to the page.
        if (!ModelState.IsValid)
        {
            RepopulateViewData();
            return Page();
        }

        //Begin transaction
        using var transaction = await _context.Database.BeginTransactionAsync();

        //Try to add the image to the database and save the file to the images folder.
        try
        {
            if (AnimalPic.File != null)
            {
                //Get the animal name based on the animal ID the user selected
                var AnimalName = _context.Animal.Where(a => a.AnimalId == AnimalPic.AnimalId).Select(a => a.Name).FirstOrDefault();

                //if the name comes up empty, return an error
                if (string.IsNullOrEmpty(AnimalName))
                {
                    TempData["ErrorMessage"] = "Animal not found.";
                    await transaction.RollbackAsync();
                    RepopulateViewData();
                    return Page();
                }

                // Get the count of images for this animal currently in the database
                var ImageCount = _context.AnimalPic.Where(a => a.AnimalId == AnimalPic.AnimalId).Count();
                ImageCount++;

                // Generate a unique file name for the uploaded image
                // Format is AnimalID + "_" + Name + "_#" + extension, where # is the image number.
                // This is stored in the database.
                AnimalPic.FileName = $"{AnimalPic.AnimalId}_{AnimalName}_{ImageCount}{Path.GetExtension(AnimalPic.File.FileName)}";

                // Set the file path to the "images" folder in the wwwroot directory
                // This is stored in the database.
                AnimalPic.FilePath = Path.Combine("images", AnimalPic.FileName);

                // Save the uploaded file to the images folder.
                var FullPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", AnimalPic.FilePath);
                using (var FileStream = new FileStream(FullPath, FileMode.Create))
                {
                    await AnimalPic.File.CopyToAsync(FileStream);
                }

                // Save the AnimalPic object to the database
                await _repository.AddAnimalPicAsync(AnimalPic.AnimalId, AnimalPic);

                ModelState.Clear();
                //Commit the transaction
                await transaction.CommitAsync();
                TempData["SuccessMessage"] = "Image submitted successfully!";
                RepopulateViewData();
                return Page();
            }
            //If the file is null for any reason, return an error.
            else
            {
                TempData["ErrorMessage"] = "No file selected.";
                await transaction.RollbackAsync();
                RepopulateViewData();
                return Page();
            }
        }
        //Catch any SQL exceptions, return an error, and rollback the transaction.
        catch (SqlException ex)
        {
            TempData["ErrorMessage"] = ex.Message;
            //Rollback the transaction
            await transaction.RollbackAsync();
            RepopulateViewData();
            return Page();
        }
    }
}

Safari.Web/Pages/Details.cshtml
@*This is the Details page, which displays whenever a user clicks the appropriate link for an animal from a list.*@

@page
@model Safari.Web.Pages.DetailsPageModel
@{
    ViewData["Title"] = "Details for " + Model.Animal.Name;
}

<h1>@Html.DisplayFor(model => model.Animal.Name)</h1>
<hr />

@*If the animal has a picture, create a Bootstrap carousel that will contain that pictures along with any others.
    A carousel is a slideshow of images that the user can click through by using arrows on the side of the images,
    and it is a part of the Bootstrap CSS framework.
*@
@if (Model.PicExists)
{
    <div id="carouselExample" class="carousel slide" style="max-width:50%">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="@Model.AnimalPics[0].FilePath" class="d-block w-100" alt="@Model.AnimalPics[0].AltText">
            </div>
            @for (int i = 1; i < Model.AnimalPics.Count; i++)
            {
                <div class="carousel-item">
                    <img src="@Model.AnimalPics[i].FilePath" class="d-block w-100" alt="@Model.AnimalPics[i].AltText">
                </div>
            }
            )
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
}
<br />
<br />

@*Render the description of the animal. In the database, this is stored as HTML, so the raw HTML can be used here.*@
<h4>Description</h4>
<br />
@Html.Raw(Model.AnimalDescription)
<br />

<h4>Key Stats:</h4>
<br />
<p>Average Lifespan: @Model.Animal.Lifespan</p>
<p>Average Height: @Model.Animal.Height</p>
<p>Average Weight: @Model.Animal.Weight</p>
<p>Average Length: @Model.Animal.Length</p>
<br />

@*List any states the animal can be found in.*@
<h4>Locations:</h4>
<br />
<p>
    The @Model.Animal.Name can be found in the following state(s):
    @string.Join(", ", Model.AnimalStates)
</p>

Safari.Web/Pages/Index.cshtml
@*This is the home page, which is displayed first when the user reaches the website.*@

@page
@model IndexPageModel
@{
    ViewData["Title"] = "Home page";
}

<div class="container-fluid text-center">
    <h1 class="display-4">Welcome to Safari Across America!</h1>
    <img class="mx-auto img-fluid" src=".\images\SafariAcrossAmerica.jpg" style="max-width: 50%; height: auto;" />
</div>
<br />
<br />
<div class="container-fluid text-center">
    <div>
        <div class="row">
            <div class="col-md-6">
                <a class="btn btn-primary btn-lg btn-home" asp-page="ViewAnimals">View All Animals</a> <br /><br />
            </div>
            <div class="col-md-6">
                <a class="btn btn-primary btn-lg btn-home" asp-page="SubmitAnimal">Submit an Animal</a> <br /><br />
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <a class="btn btn-primary btn-lg btn-home" asp-page="Map">Interactive Map</a>
            </div>
            <div class="col-md-6">
                <a class="btn btn-primary btn-lg btn-home" asp-page="SubmitImage">Submit an Image</a> <br /><br />
            </div>
        </div>
    </div>
</div>

Safari.Web/Pages/SubmitAnimal.cshtml
@*This is the Submit Animal page, which allows users to submit an animal to the website.
    The animal is added to the database as an unapproved record. Admin approval is required for it to be viewable on
    pages such as View All Animals and the Interactive Map.*@

@page
@model Safari.Web.Pages.SubmitAnimalPageModel

@{
    ViewData["Title"] = "Submit Animal";
}

@if (!string.IsNullOrEmpty(TempData["ErrorMessage"] as string))
{
    <div class="alert alert-danger">
        @TempData["ErrorMessage"]
    </div>
}
else if (!string.IsNullOrEmpty(TempData["SuccessMessage"] as string))
{
    <div class="alert alert-success">
        @TempData["SuccessMessage"]
    </div>
}

@if (!ViewData.ModelState.IsValid)
{
    <div class="alert alert-danger">
        <p>Please correct the following errors:</p>
        <ul>
            @foreach (var error in ViewData.ModelState.Values.SelectMany(v => v.Errors))
            {
                <li>@error.ErrorMessage</li>
            }
        </ul>
    </div>
}

<h1>Submit an Animal</h1>

<h4>
    Help us track the exotic wildlife of the United States by submitting a new animal.<br />
    If you don't know something, it's okay to leave it blank. Only fields with a <span class="text-danger">red asterisk (*)</span> are required.
</h4>
<br />
<hr />
<br />
<div class="row">
    <div class="col-md-auto">
        <form method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Animal.Name" class="control-label">
                    Name<span class="text-danger">* </span>
                    <i class="far fa-question-circle" title="Enter the name of the animal."></i>
                </label>
                <input asp-for="Animal.Name" class="form-control" />
                @******************@
                @*Input Validation*@
                @******************@
                @*Each div in the form contains a span for input validation. This uses the JQuery Validation library
                    to validate the input on the client side. The validation is based on the data types for the model.
                    For example, Animal.Name is not a nullable string, so JQuery Validation will display an error if
                    the user tries to submit without providing it.*@                
                <span asp-validation-for="Animal.Name" class="text-danger"></span>
                <br />
            </div>

            <div class="form-group">
                <label asp-for="SelectedStateIds" class="control-label">
                    States <span class="text-danger">* </span>
                    @*Some of the fields on the form have a question mark icon. The user can hover over this to
                        view additional guidance for the field.*@
                    <i class="far fa-question-circle" title="Select the state(s) where the animal lives."></i>
                </label>
                <br />
                @*Create a multi-selector box for the Animal States, pre-filled with all states in the database.
                    This uses the Select2 JavaScript library.*@
                <select asp-for="SelectedStateIds" class="form-control" style="width: 75%" asp-items="ViewBag.StateId" multiple data-placeholder="Select states"></select>
                <br />
                <span asp-validation-for="SelectedStateIds" class="text-danger"></span>
                <br />
                <br />
            </div>

            <div class="form-group">
                <label asp-for="Animal.AnimalTypeId" class="control-label">
                    Animal Type
                    <i class="far fa-question-circle" title="What kind of animal is it? Choose from the list."></i>
                </label>
                <select asp-for="Animal.AnimalTypeId" class="form-control" asp-items="ViewBag.AnimalTypeId">
                    <option value="">Select an Animal Type</option>
                </select>
                <br />
            </div>

            <div class="form-group">
                <label asp-for="Animal.DietTypeId" class="control-label">
                    Diet
                    <i class="far fa-question-circle" title="What diet does the animal have? Choose from the list."></i>
                </label>
                <select asp-for="Animal.DietTypeId" class="form-control" asp-items="ViewBag.DietTypeId">
                    <option value="">Select a Diet Type</option>
                </select>
                <br />
            </div>

            <div class="form-group">
                <label asp-for="Animal.Weight" class="control-label">
                    Average Weight (pounds)
                </label>
                <input asp-for="Animal.Weight" class="form-control" />
                <span asp-validation-for="Animal.Weight" class="text-danger"></span>
                <br />
            </div>

            <div class="form-group">
                <label asp-for="Animal.Height" class="control-label">
                    Average Height (inches)
                </label>
                <input asp-for="Animal.Height" class="form-control" />
                <span asp-validation-for="Animal.Height" class="text-danger"></span>
                <br />
            </div>

            <div class="form-group">
                <label asp-for="Animal.Length" class="control-label">
                    Average Length (inches)
                </label>
                <input asp-for="Animal.Length" class="form-control" />
                <span asp-validation-for="Animal.Length" class="text-danger"></span>
                <br />
            </div>

            <div class="form-group">
                <label asp-for="Animal.IsEndangered" class="control-label">
                    Is the animal endangered?
                </label>
                <select asp-for="Animal.IsEndangered" class="form-control">
                    <option value="false">No</option>
                    <option value="true">Yes</option>
                </select>
                <br />
            </div>

            <div class="form-group">
                <label asp-for="Animal.Lifespan" class="control-label">
                    Average Lifespan (years)
                </label>
                <input asp-for="Animal.Lifespan" class="form-control" />
                <span asp-validation-for="Animal.Lifespan" class="text-danger"></span>
                <br />
            </div>

            <div class="form-group">
                <label asp-for="AnimalDescription.Description" class="control-label">
                    Description
                    <i class="far fa-question-circle" title="Tell us a little about the animal. This is your chance to share fun facts!"></i>
                </label>
                <textarea asp-for="AnimalDescription.Description" class="form-control" id="AnimalDescriptionEditor"></textarea>
                <span asp-validation-for="AnimalDescription.Description" class="text-danger"></span>
                <span asp-validation-for="AnimalDescription" class="text-danger"></span>
                <br />
            </div>

            <div class="form-group">
                <label asp-for="AnimalPic.File" class="control-label">
                    Image File
                    <i class="far fa-question-circle" title="Upload a royalty-free picture of the animal."></i>
                </label>
                <br />
                <input asp-for="AnimalPic.File" type="file" class="form-control-file" accept="image/*" />
                <span asp-validation-for="AnimalPic.File" class="text-danger"></span>
                <span asp-validation-message="AnimalPic.File" class="text-danger"></span>
                <br />
                <br />
            </div>

            <div class="form-group">
                <label asp-for="AnimalPic.AltText" class="control-label">Caption for the Image. If you need to cite a copyright or other credit, do so here.</label>
                <input asp-for="AnimalPic.AltText" class="form-control" />
                <span asp-validation-for="AnimalPic.AltText" class="text-danger"></span>
                <br />
            </div>

            <div class="form-group">
                <label asp-for="AnimalPic.Source" class="control-label">
                    Where did you get the picture from?
                    <i class="far fa-question-circle" title="If you took the photo yourself, enter 'Self.' If you got the picture from a website, please provide the link, or provide the copyright information."></i>
                </label>
                <input asp-for="AnimalPic.Source" class="form-control" />
                <span asp-validation-for="AnimalPic.Source" class="text-danger"></span>
                <br />
            </div>
            <div class="row">
                <div class="col-md-4">
                    <input type="submit" value="Submit Animal" class="btn btn-success" />
                </div>
                <div class="col-md-4">
                    <input type="reset" value="Reset Form" class="btn btn-danger"
                           asp-page-handler="ResetForm" asp-page="SubmitAnimal" onclick="window.scrollTo(0, 0);" />
                </div>
                <div class="col-md-4">
                    <a class="btn btn-secondary" asp-page="Index">Back to Home</a>
                </div>
            </div>
    </form>
</div>
</div>


@*The JavaScript for this page adds the ValidationScriptsPartial partial view, which imports the JQuery Validation libraries.
    It also configures the TinyMCE editor for the animal description with some custom settings for the toolbar and plugins.*@

@section Scripts
    {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <script>
        $(document).ready(function () {
            $('select[multiple]').select2();
        });

        tinymce.init({
            selector: '#AnimalDescriptionEditor',
            height: 300,
            menubar: false,
            plugins: 'advlist autolink lists link image imagetools charmap print preview',
            toolbar: 'undo redo | formatselect | bold italic underline | alignleft aligncenter alignright alignjustify | bullist numlist | link image'
        });
    </script>

}